---
AWSTemplateFormatVersion: "2010-09-09"

Description: S3 Template to use

Parameters:
  S3BucketName:
    Type: String
    Description: 'S3Bucket Name Param'
  Application:
    Type: String
    Description: 'Application Name'
Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      Tags:
        -
          Key: Organization
          Value: IT
        -
          Key: Owner
          Value: Bob
        -
          Key: App
          Value: !Ref Application
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the S3 Bucket
  BucketArn:
    Value: S3Bucket.arn
